
export const metadata = {
    title: "Staff Information",
    description: "Generated by create next app",
  };

export default function Staff(){
    return(
        <div>
            <h1>Information for staff</h1>
    <h2>News</h2>
    <p>Cantor College recently hosted the Software Engineering student of the year awards. Short-
        listed candidates from around the country attended the one day event.
    </p>
    <h3>Academic Registry</h3>
    <p>
        For academic regulations, assessment, awards, student records and course validation.
    </p>
    <h4>Catering Services</h4>
    <p>
        Contact the Catering Services regarding on and off-site catering.
    </p>
    <h5><b>Financial Services</b></h5>
    <p>
        The financial team based on the 2nd Floor are responsible for all areas of student finance as
        well as College budgeting.
    </p>
    <h6><b>Information Systems Services</b></h6>
    <p>
        The ISS team delivers the College’s computing facilities including all hardware and software.
        They also run the staff helpdesk.
    </p>
    <h5><b>Marketing Services</b></h5>
    <p>
        The Marketing Team will help promote events and new courses. They will help with press
        release preparation.
    </p>
    <h5><b>Personnel Services</b></h5>
    <p>
        All staff pay and conditions enquiries should be directed to the Personnel Services team on
        the 3rd floor.
    </p>
    <h5><b>Facilities</b></h5>
    <p>
        The facilities are responsible for the general care and maintenance of the College. All
        enquiries via the main helpdesk.
    </p>
        </div>
    )
  }